import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Import boundary: the service-role Supabase client factory may only be
  // imported from Route Handlers (`app/api/**/route.ts`). Enforced via
  // no-restricted-imports.
  {
    files: ["**/*.ts", "**/*.tsx"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@/lib/supabase/service",
              message:
                "The service-role Supabase client may only be imported from Route Handlers (files under app/api/**/route.ts).",
            },
          ],
        },
      ],
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
  // Allow Route Handlers to import the service-role client. This override
  // applies only to files matching the Route Handler convention.
  {
    files: ["app/api/**/route.ts"],
    rules: {
      "no-restricted-imports": "off",
    },
  },
  // Import boundary: Zustand slices in lib/store are framework-agnostic and
  // must not import React. They also must never import
  // the service-role client (inherited restriction kept in the paths list).
  {
    files: ["lib/store/**/*.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@/lib/supabase/service",
              message:
                "The service-role Supabase client may only be imported from Route Handlers (files under app/api/**/route.ts).",
            },
            {
              name: "react",
              message:
                "Zustand slices in lib/store must not import React — they are framework-agnostic state containers.",
            },
          ],
        },
      ],
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Transient artifacts generated by the Supabase CLI (`supabase start`).
    "supabase/.temp/**",
  ]),
]);

export default eslintConfig;
